/* Generated by AN DISI Unibo */ 
package it.unibo.nor2

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Nor2 ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var Value = 1 
			   var CurR  = 0
			   var CurB  = 0
			   
			   fun norf( ){
			   	 if( CurR==0 && CurB==0 ) Value = 1
			   	 else Value = 0
			   }	 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						forward("a", "a(0)" ,"nor1" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="elabInputR",cond=whenDispatch("r"))
					transition(edgeName="t03",targetState="elabInputB",cond=whenDispatch("b"))
				}	 
				state("work") { //this:State
					action { //it:State
						 norf()  
						CommUtils.outmagenta("		$name | $Value")
						delay(500) 
						forward("a", "a($Value)" ,"nor1" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("elabInputR") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("r(X)"), Term.createTerm("r(0)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurR = 0  
						}
						if( checkMsgContent( Term.createTerm("r(X)"), Term.createTerm("r(1)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurR = 1  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("elabInputB") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | elabInputB ${currentMsg.msgContent()}")
						if( checkMsgContent( Term.createTerm("b(X)"), Term.createTerm("b(0)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurB = 0  
						}
						if( checkMsgContent( Term.createTerm("b(X)"), Term.createTerm("b(1)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurB = 1  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
} 
