/* Generated by AN DISI Unibo */ 
package it.unibo.pingev

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Pingev ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 val display = DisplayData.create()
		 var N = 1 ; val TMAX = 3000L;
			   var StartTime = 0L; var Elapsed= 0L 
			   var map = HashMap<Int, Int>()
			   val Obs = main.java.PingData()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outblue("$name sends $N  ")
						 display.print("$name emits $N")  
						StartTime = getCurrentTime()
						emit("ball", "ball($N)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="receive", cond=doswitch() )
				}	 
				state("receive") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_receive", 
				 	 					  scope, context!!, "local_tout_"+name+"_receive", TMAX )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="endofexchange",cond=whenTimeout("local_tout_"+name+"_receive"))   
					transition(edgeName="t01",targetState="reply",cond=whenEvent("ball"))
				}	 
				state("reply") { //this:State
					action { //it:State
						Elapsed = getDuration(StartTime)
						 Obs.addToHistory(""+Elapsed)   
						if( checkMsgContent( Term.createTerm("ball(N)"), Term.createTerm("ball(V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblue("$name perceives ${payloadArg(0)}} $Elapsed")
								 display.print("$name perceives ${payloadArg(0)} $Elapsed")  
						}
						 N = N + 1  
						CommUtils.outblue("$name sends $N  ")
						 display.print("$name emits $N")  
						emit("ball", "ball($N)" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="receive", cond=doswitch() )
				}	 
				state("endofexchange") { //this:State
					action { //it:State
						updateResourceRep( "ball(0)"  
						)
						 Obs.showHistory()  
						 display.setReady(Obs)  
						CommUtils.outblue("$name ENDS ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
