/* Generated by AN DISI Unibo */ 
package it.unibo.latchusagefig

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Latchusagefig ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outcyan("s0 | START")
						delay(1000) 
						CommUtils.outcyan(" 00 (stato inziale) ")
						request("latchdo", "latchdo(0,0)" ,"latch" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t014",targetState="s1",cond=whenReply("latchval"))
				}	 
				state("s1") { //this:State
					action { //it:State
						CommUtils.outred("s0 | ${currentMsg.msgContent()}")
						CommUtils.outcyan(" RESET 1 ........................ ")
						request("latchdo", "latchdo(0,1)" ,"latch" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t015",targetState="s2",cond=whenReply("latchval"))
				}	 
				state("s2") { //this:State
					action { //it:State
						CommUtils.outred("s1 | ${currentMsg.msgContent()}")
						CommUtils.outcyan(" RESET 0 ........................ ")
						request("latchdo", "latchdo(0,0)" ,"latch" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t016",targetState="s3",cond=whenReply("latchval"))
				}	 
				state("s3") { //this:State
					action { //it:State
						CommUtils.outred("s2 | ${currentMsg.msgContent()}")
						CommUtils.outcyan(" SET1 ........................ ")
						request("latchdo", "latchdo(1,0)" ,"latch" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t017",targetState="s4",cond=whenReply("latchval"))
				}	 
				state("s4") { //this:State
					action { //it:State
						CommUtils.outred("s3 | ${currentMsg.msgContent()}")
						CommUtils.outcyan(" SET0 ........................ ")
						request("latchdo", "latchdo(0,0)" ,"latch" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t018",targetState="s5",cond=whenReply("latchval"))
				}	 
				state("s5") { //this:State
					action { //it:State
						CommUtils.outred("s4 | ${currentMsg.msgContent()}")
						CommUtils.outcyan(" RESET 1 ........................ ")
						request("latchdo", "latchdo(0,1)" ,"latch" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t019",targetState="s6",cond=whenReply("latchval"))
				}	 
				state("s6") { //this:State
					action { //it:State
						CommUtils.outred("s5 | ${currentMsg.msgContent()}")
						CommUtils.outcyan(" RESET 0 ........................ ")
						request("latchdo", "latchdo(0,0)" ,"latch" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t020",targetState="s7",cond=whenReply("latchval"))
				}	 
				state("s7") { //this:State
					action { //it:State
						CommUtils.outred("s6 | ${currentMsg.msgContent()}  ")
						CommUtils.outcyan(" SET0 ........................ ")
						request("latchdo", "latchdo(0,0)" ,"latch" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t021",targetState="end",cond=whenReply("latchval"))
				}	 
				state("end") { //this:State
					action { //it:State
						CommUtils.outred("s7 end | ${currentMsg.msgContent()}")
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
