/* Generated by AN DISI Unibo */ 
package it.unibo.caller

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Caller ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 val N = 43 
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						delay(3000) 
						CommUtils.outblue("$name | request ")
						request("dofibo", "dofibo($N)" ,"servicemath" )  
						CommUtils.outblue("$name | request ")
						request("dofibo", "dofibo(23)" ,"servicemath" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="fiboanswer",cond=whenReply("fibodone"))
				}	 
				state("fiboanswer") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("fibodone(CALLER,N,RESULT,TIME)"), Term.createTerm("fibodone(CALLER,V,R,T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                   val Sender = payloadArg(0)
								                   val N = payloadArg(1)
								                   val R = payloadArg(2)
								                   val T = payloadArg(3)
								                   val outS = "fiboanswer for N=${N} calledby ${Sender}:${R} time=${T}"
								                   val SOUT = "$name | $outS "
								CommUtils.outblue(" $SOUT")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="fiboanswer",cond=whenReply("fibodone"))
				}	 
			}
		}
} 
