/* Generated by AN DISI Unibo */ 
package it.unibo.basicrobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Basicrobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "ss0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 val robot = uniborobots.robotSupport
		  
		  var StepTime      = 0L
		  var StartTime     = 0L     
		  var Duration      = 0L   
		  var RobotType     = "" 
		  var CurrentMove   = "unkknown"
		  var StepSynchRes  = false
		  var OwnerMngr     = supports.OwnerManager //Kotlin object
		  var AnswerKo      = "" 
		  
		  fun checkOwner( ) : Boolean {
		  	return OwnerMngr.checkOwner( currentMsg.msgSender() )
		  }
		return { //this:ActionBasciFsm
				state("ss0") { //this:State
					action { //it:State
						discardMessages = true
						delay(2000) 
						delegate("engage", "engager") 
						delegate("disengage", "engager") 
						delegate("doplan", "planexec") 
						delegate("getrobotstate", "robotpos") 
						delegate("setrobotstate", "robotpos") 
						delegate("moverobot", "robotpos") 
						delegate("setdirection", "robotpos") 
						delegate("getenvmap", "robotpos") 
						subscribeToLocalActor("basicrobot") 
						 robot.create(myself,"basicrobotConfig.json")  
						 RobotType = robot.robotKind  
						robot.move( "h"  )
						delay(300) 
						robot.move( "a"  )
						robot.move( "d"  )
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("waitForRobot") { //this:State
					action { //it:State
						delay(5000) 
						CommUtils.outmagenta("basicrobot | STARTING ... ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						discardMessages = false
						CommUtils.outmagenta("basicrobot  | waiting, working for ${OwnerMngr.owner} ... ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="doStep",cond=whenRequest("step"))
					transition(edgeName="t04",targetState="execcmd",cond=whenDispatch("cmd"))
					transition(edgeName="t05",targetState="endwork",cond=whenDispatch("end"))
					transition(edgeName="t06",targetState="handlesonardata",cond=whenEvent("sonardata"))
				}	 
				state("handlesonardata") { //this:State
					action { //it:State
						CommUtils.outyellow("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("sonar(DISTANCE)"), Term.createTerm("sonar(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								updateResourceRep( "sonar(${payloadArg(0)})"  
								)
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("execcmd") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if(    checkOwner()  
						 ){if( checkMsgContent( Term.createTerm("cmd(MOVE)"), Term.createTerm("cmd(MOVE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentMove = payloadArg(0)  
								robot.move( payloadArg(0)  )
								updateResourceRep( "moveactivated(${payloadArg(0)})"  
								)
						}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("doStep") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if(    checkOwner()  
						 ){if( checkMsgContent( Term.createTerm("step(TIME)"), Term.createTerm("step(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
									StepTime     = payloadArg(0).toLong()  	 
								updateResourceRep( "step(${StepTime})"  
								)
						}
						StartTime = getCurrentTime()
						 StepSynchRes = robot.dostep( StepTime )  
						}
						else
						 { AnswerKo = "youarenotowner"  
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="stepok", cond=doswitchGuarded({ StepSynchRes  
					}) )
					transition( edgeName="goto",targetState="stepKo", cond=doswitchGuarded({! ( StepSynchRes  
					) }) )
				}	 
				state("stepok") { //this:State
					action { //it:State
						 StepSynchRes = false  
						robot.move( "h"  )
						updateResourceRep( "stepDone($StepTime)"  
						)
						answer("step", "stepdone", "stepdone($StepTime)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("stepKo") { //this:State
					action { //it:State
						if(  AnswerKo == ""  
						 ){Duration = getDuration(StartTime)
						robot.move( "h"  )
						 var TunedDuration   = StepTime - ((Duration * 0.80)).toLong()    
						if(  TunedDuration > 30  
						 ){robot.move( "s"  )
						delay(TunedDuration)
						robot.move( "h"  )
						updateResourceRep( "stepFail($Duration)"  
						)
						delay(300) 
						}
						answer("step", "stepfailed", "stepfailed($Duration,obst)"   )  
						}
						else
						 {answer("step", "stepfailed", "stepfailed($Duration,$AnswerKo)"   )  
						  AnswerKo = ""  
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("endwork") { //this:State
					action { //it:State
						updateResourceRep( "basicrobot(end)"  
						)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
