/* Generated by AN DISI Unibo */ 
package it.unibo.latchusage

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Latchusage ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | START")
						delay(1000) 
						request("latchdo", "latchdo(0,0)" ,"latch" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t014",targetState="s1",cond=whenReply("latchval"))
				}	 
				state("s1") { //this:State
					action { //it:State
						CommUtils.outcyan(" 00 (stato inziale) ")
						CommUtils.outmagenta("$name | ${currentMsg.msgContent()}")
						CommUtils.outcyan("s1 - RESET 1 ........................ ")
						forward("reset", "reset(1)" ,"latch" ) 
						delay(500) 
						CommUtils.outcyan("s2 - RESET 0 ........................ ")
						forward("reset", "reset(0)" ,"latch" ) 
						delay(500) 
						CommUtils.outcyan("s3 - SET 1 ........................ ")
						forward("set", "set(1)" ,"latch" ) 
						delay(500) 
						CommUtils.outcyan("s4 - SET 0 ........................ ")
						forward("set", "set(0)" ,"latch" ) 
						delay(500) 
						CommUtils.outcyan("s5 - RESET 1 ........................ ")
						forward("reset", "reset(1)" ,"latch" ) 
						delay(500) 
						CommUtils.outcyan("s6 - RESET 0 ........................ ")
						forward("reset", "reset(0)" ,"latch" ) 
						delay(500) 
						CommUtils.outcyan("s7 - SET 0 ........................ ")
						request("latchdo", "latchdo(0,0)" ,"latch" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t015",targetState="end",cond=whenReply("latchval"))
				}	 
				state("end") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name end | ${currentMsg.msgContent()}")
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
