/* Generated by AN DISI Unibo */ 
package it.unibo.cleaner24

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024
import main.resources.map.RoomMap
import main.resources.map.RobotDir
import main.resources.map.RobotDir.Direction

class Cleaner24 ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "activate"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
			var GoingDown   = true 
		
		    lateinit var map : RoomMap
			var PX = 0   //Robot pos along X
			var PY = 0   //Robot pos along Y
		return { //this:ActionBasciFsm
				state("activate") { //this:State
					action { //it:State
						  
						           GoingDown = true 
						           RobotDir.setDir( Direction.DOWN )
						CommUtils.outblue("$name | START ")
						  map = RoomMap.loadRoomMap("map")  
						  map.clear()     
						  map.setRobot(PX,PY)  
						  map.showMap()      
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="coverColumn", cond=doswitch() )
				}	 
				state("coverColumn") { //this:State
					action { //it:State
						 map.setCellClean(PX,PY)   
						delay(300) 
						request("step", "step(350)" ,"robot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="stepColumnDone",cond=whenReply("stepdone"))
					transition(edgeName="t03",targetState="turn",cond=whenReply("stepfailed"))
				}	 
				state("stepColumnDone") { //this:State
					action { //it:State
						 if(GoingDown) PX++; else PX--  
						 map.setRobot(PX,PY)       
						 map.setCellClean(PX,PY)   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="coverColumn", cond=doswitch() )
				}	 
				state("turn") { //this:State
					action { //it:State
						CommUtils.outblack("turn while GoingDown=$GoingDown")
						if(  GoingDown  
						 ){forward("cmd", "cmd(s)" ,"robot" ) 
						forward("cmd", "cmd(l)" ,"robot" ) 
						}
						else
						 {forward("cmd", "cmd(r)" ,"robot" ) 
						 }
						delay(300) 
						request("step", "step(350)" ,"robot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="doTurn",cond=whenReply("stepdone"))
					transition(edgeName="t05",targetState="lastColumn",cond=whenReply("stepfailed"))
				}	 
				state("doTurn") { //this:State
					action { //it:State
						CommUtils.outmagenta("doTurn while GoingDown=$GoingDown")
						  PY++; 
						    		map.setCellClean(PX,PY)  
						if(  GoingDown  
						 ){forward("cmd", "cmd(l)" ,"robot" ) 
						}
						else
						 {forward("cmd", "cmd(r)" ,"robot" ) 
						 }
						delay(300) 
						  GoingDown = ! GoingDown 
						   			if( GoingDown ) RobotDir.setDir(Direction.DOWN) 
						   			else RobotDir.setDir(Direction.UP) 
						request("step", "step(350)" ,"robot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="continueAfterTurn",cond=whenReply("stepdone"))
					transition(edgeName="t07",targetState="lastColumn",cond=whenReply("stepfailed"))
				}	 
				state("continueAfterTurn") { //this:State
					action { //it:State
						 if(GoingDown) PX++; else PX--  
						 map.setCellClean(PX,PY)   
						 map.showMap()   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="coverColumn", cond=doswitch() )
				}	 
				state("lastColumn") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						  PY++; 
						    		map.setCellClean(PX,PY)  
						if(  GoingDown  
						 ){forward("cmd", "cmd(l)" ,"robot" ) 
						}
						else
						 {forward("cmd", "cmd(r)" ,"robot" ) 
						 }
						 map.showMap()   
						delay(200) 
						  GoingDown = ! GoingDown   	 
						   			if( GoingDown ) RobotDir.setDir(Direction.DOWN) 
						   			else RobotDir.setDir(Direction.UP) 
						request("step", "step(350)" ,"robot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="coverLastColumn",cond=whenReply("stepdone"))
					transition(edgeName="t09",targetState="endofwork",cond=whenReply("stepfailed"))
				}	 
				state("coverLastColumn") { //this:State
					action { //it:State
						 if(GoingDown) PX++; else PX--  
						 map.setCellClean(PX,PY)   
						delay(200) 
						request("step", "step(350)" ,"robot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t010",targetState="coverLastColumn",cond=whenReply("stepdone"))
					transition(edgeName="t011",targetState="endofwork",cond=whenReply("stepfailed"))
				}	 
				state("endofwork") { //this:State
					action { //it:State
						CommUtils.outblue("---------------------------")
						 map.showMap()   
						 val MS  = map.toProlog()   
						 map.saveRoomMapProlog("mapcleanedkb", MS )  
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("fatalError") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
