version: '3'
services:
  servicemathasynch:
    image: docker.io/natbodocker/servicemath:1.0
    #image: servicemath:1.0
    ports:
      - 8011:8011/tcp
      - 8011:8011/udp
      - 8088:8088 

## docker-compose -f servicemathAsynch.yaml  up
