cell(c_0_0,ctxconwayactors).
cell(c_0_1,ctxconwayactors).
cell(c_0_2,ctxconwayactors).
cell(c_0_3,ctxconwayactors).
cell(c_0_4,ctxconwayactors).
cell(c_0_5,ctxconwayactors).
cell(c_0_6,ctxconwayactors).
cell(c_0_7,ctxconwayactors).
cell(c_0_8,ctxconwayactors).
cell(c_1_0,ctxconwayactors).
cell(c_1_1,ctxconwayactors).
cell(c_1_2,ctxconwayactors).
cell(c_1_3,ctxconwayactors).
cell(c_1_4,ctxconwayactors).
cell(c_1_5,ctxconwayactors).
cell(c_1_6,ctxconwayactors).
cell(c_1_7,ctxconwayactors).
cell(c_1_8,ctxconwayactors).
cell(c_2_0,ctxconwayactors).
cell(c_2_1,ctxconwayactors).
cell(c_2_2,ctxconwayactors).
cell(c_2_3,ctxconwayactors).
cell(c_2_4,ctxconwayactors).
cell(c_2_5,ctxconwayactors).
cell(c_2_6,ctxconwayactors).
cell(c_2_7,ctxconwayactors).
cell(c_2_8,ctxconwayactors).
cell(c_3_0,ctxconwayactors).
cell(c_3_1,ctxconwayactors).
cell(c_3_2,ctxconwayactors).
cell(c_3_3,ctxconwayactors).
cell(c_3_4,ctxconwayactors).
cell(c_3_5,ctxconwayactors).
cell(c_3_6,ctxconwayactors).
cell(c_3_7,ctxconwayactors).
cell(c_3_8,ctxconwayactors).
cell(c_4_0,ctxconwayactors).
cell(c_4_1,ctxconwayactors).
cell(c_4_2,ctxconwayactors).
cell(c_4_3,ctxconwayactors).
cell(c_4_4,ctxconwayactors).
cell(c_4_5,ctxconwayactors).
cell(c_4_6,ctxconwayactors).
cell(c_4_7,ctxconwayactors).
cell(c_4_8,ctxconwayactors).
cell(c_5_0,ctxconwayactors).
cell(c_5_1,ctxconwayactors).
cell(c_5_2,ctxconwayactors).
cell(c_5_3,ctxconwayactors).
cell(c_5_4,ctxconwayactors).
cell(c_5_5,ctxconwayactors).
cell(c_5_6,ctxconwayactors).
cell(c_5_7,ctxconwayactors).
cell(c_5_8,ctxconwayactors).
cell(c_6_0,ctxconwayactors).
cell(c_6_1,ctxconwayactors).
cell(c_6_2,ctxconwayactors).
cell(c_6_3,ctxconwayactors).
cell(c_6_4,ctxconwayactors).
cell(c_6_5,ctxconwayactors).
cell(c_6_6,ctxconwayactors).
cell(c_6_7,ctxconwayactors).
cell(c_6_8,ctxconwayactors).
cell(c_7_0,ctxconwayactors).
cell(c_7_1,ctxconwayactors).
cell(c_7_2,ctxconwayactors).
cell(c_7_3,ctxconwayactors).
cell(c_7_4,ctxconwayactors).
cell(c_7_5,ctxconwayactors).
cell(c_7_6,ctxconwayactors).
cell(c_7_7,ctxconwayactors).
cell(c_7_8,ctxconwayactors).
cell(c_8_0,ctxconwayactors).
cell(c_8_1,ctxconwayactors).
cell(c_8_2,ctxconwayactors).
cell(c_8_3,ctxconwayactors).
cell(c_8_4,ctxconwayactors).
cell(c_8_5,ctxconwayactors).
cell(c_8_6,ctxconwayactors).
cell(c_8_7,ctxconwayactors).
cell(c_8_8,ctxconwayactors).
