/* Generated by AN DISI Unibo */ 
package it.unibo.caller_test

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Caller_test ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		  var SOUT = ""
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						delay(10000) 
						 SOUT = "$name | 44"   
						forward("out", "out($SOUT)" ,"display" ) 
						request("dofibo", "dofibo(44)" ,"servicemath" )  
						delay(1000) 
						 SOUT = "$name | 38"   
						forward("out", "out($SOUT)" ,"display" ) 
						request("dofibo", "dofibo(50)" ,"servicemath" )  
						delay(1000) 
						 SOUT = "$name | 40"   
						forward("out", "out($SOUT)" ,"display" ) 
						request("dofibo", "dofibo(5)" ,"servicemath" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="fiboanswer",cond=whenReply("fibodone"))
					transition(edgeName="t05",targetState="handleAskFromreceiver",cond=whenRequest("confirm"))
				}	 
				state("fiboanswer") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("fibodone(CALLER,N,RESULT,TIME)"), Term.createTerm("fibodone(CALLER,V,R,T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 SOUT = "$name | fiboanswer for ${payloadArg(1)} from ${payloadArg(0)}=${payloadArg(2)} time=${payloadArg(3)}"  
								forward("out", "out($SOUT)" ,"display" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t06",targetState="fiboanswer",cond=whenReply("fibodone"))
					transition(edgeName="t07",targetState="handleAskFromreceiver",cond=whenRequest("confirm"))
				}	 
				state("handleAskFromreceiver") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("confirm(X)"), Term.createTerm("confirm(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								if(  payloadArg(0).toInt() > 45  
								 ){answer("confirm", "confirmed", "confirmed(no)"   )  
								}
								else
								 {answer("confirm", "confirmed", "confirmed(yes)"   )  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="fiboanswer",cond=whenReply("fibodone"))
				}	 
			}
		}
} 
