/* Generated by AN DISI Unibo */ 
package it.unibo.ctxhello
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	//System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "ERROR");
	QakContext.createContexts(
	        "localhost", this, "helloworld4.pl", "sysRules.pl", "ctxhello"
	)
	//OCT2023 Facade
	//JAN24 Display
}

