/* Generated by AN DISI Unibo */ 
package it.unibo.ctxservice
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	//System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "ERROR");
	QakContext.createContexts(
	        "localhost", this, "servicemathasking.pl", "sysRules.pl", "ctxservice"
	)
	//OCT2023 Facade
	//JAN24 Display
	unibo.qakdisplaygui24.QakFacadeApplication.main( arrayOf<String>() );
}

