/* Generated by AN DISI Unibo */ 
package it.unibo.pong

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Pong ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var N = -1  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name STARTS ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="receiveball",cond=whenEvent("startgame"))
				}	 
				state("receiveball") { //this:State
					action { //it:State
						CommUtils.outgreen("$name receieveball  ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="endgame",cond=whenEvent("stopgame"))
					transition(edgeName="t02",targetState="answerback",cond=whenDispatch("ball"))
				}	 
				state("answerback") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("ball(N)"), Term.createTerm("ball(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 N = payloadArg(0).toInt()  
						}
						if(  N > 0  
						 ){delay(300) 
						CommUtils.outgreen("$name answerback $N ")
						forward("ball", "ball($N)" ,"ping" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="receiveball", cond=doswitchGuarded({ N > 0  
					}) )
					transition( edgeName="goto",targetState="endgame", cond=doswitchGuarded({! ( N > 0  
					) }) )
				}	 
				state("endgame") { //this:State
					action { //it:State
						CommUtils.outblue("$name BYE  ")
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
