/* Generated by AN DISI Unibo */ 
package it.unibo.norusage

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Norusage ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(400) 
						CommUtils.outmagenta("soff ----------- ")
						forward("s", "s(0)" ,"nor" ) 
						delay(2000) 
						CommUtils.outmagenta("son  ----------- ")
						forward("s", "s(1)" ,"nor" ) 
						delay(2000) 
						CommUtils.outmagenta("soff ----------- ")
						forward("s", "s(0)" ,"nor" ) 
						delay(2000) 
						CommUtils.outmagenta("son  ----------- ")
						forward("s", "s(1)" ,"nor" ) 
						delay(3000) 
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
