/* Generated by AN DISI Unibo */ 
package it.unibo.caller

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Caller ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						delay(4000) 
						request("dofibo", "dofibo(43)" ,"servicemath" )  
						request("dofibo", "dofibo(60)" ,"servicemath" )  
						request("dofibo", "dofibo(47)" ,"servicemath" )  
						request("dofibo", "dofibo(5)" ,"servicemath" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="fiboanswer",cond=whenReply("fibodone"))
					transition(edgeName="t01",targetState="handleAskFromreceiver",cond=whenRequest("confirm"))
				}	 
				state("fiboanswer") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("fibodone(CALLER,N,RESULT,TIME)"), Term.createTerm("fibodone(CALLER,V,R,T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val Sender = payloadArg(0)
								                val N = payloadArg(1)
								                val R = payloadArg(2)
								                val T = payloadArg(3)    
								                val outS = "fiboanswer for N=${N} by ${Sender}:${R} time=${T}"    
								                val SOUT = "$name | $outS"      
								CommUtils.outmagenta("$SOUT")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="fiboanswer",cond=whenReply("fibodone"))
					transition(edgeName="t03",targetState="handleAskFromreceiver",cond=whenRequest("confirm"))
				}	 
				state("handleAskFromreceiver") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("confirm(X)"), Term.createTerm("confirm(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val N = payloadArg(0).toInt()  
								if(  N > 45 && N < 55  
								 ){answer("confirm", "confirmed", "confirmed(yes)"   )  
								}
								else
								 {answer("confirm", "confirmed", "confirmed(no)"   )  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t04",targetState="fiboanswer",cond=whenReply("fibodone"))
					transition(edgeName="t05",targetState="handleAskFromreceiver",cond=whenRequest("confirm"))
				}	 
			}
		}
} 
