/* Generated by AN DISI Unibo */ 
package it.unibo.caller2

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

class Caller2 ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var N    = 40 
		       var SOUT = ""
				
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						delay(4000) 
						 SOUT = "$name | starts " 
						forward("out", "out($SOUT)" ,"display" ) 
						request("dofibo", "dofibo($N)" ,"servicemath" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t03",targetState="fiboanswer",cond=whenReply("fibodone"))
				}	 
				state("fiboanswer") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("fibodone(CALLER,N,R)"), Term.createTerm("fibodone(CALLER,V,R)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val SOUT = "$name | fiboanswer for ${payloadArg(1)}/from ${payloadArg(0)}=${payloadArg(2)}"  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
