/* Generated by AN DISI Unibo */ 
package it.unibo.nor1

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Nor1 ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var Value = 3 
			   var CurS  = 0
			   var CurA  = 0
			   
			   fun norf( ){
			   	 if( CurS==0 && CurA==0 ) Value = 1
			   	 else Value = 0
			   }	 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(100) 
						forward("b", "b(0)" ,"nor2" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="elabInputS",cond=whenDispatch("s"))
					transition(edgeName="t01",targetState="elabInputA",cond=whenDispatch("a"))
				}	 
				state("work") { //this:State
					action { //it:State
						 norf()  
						CommUtils.outblue("$name | $Value")
						delay(500) 
						forward("b", "b($Value)" ,"nor2" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("elabInputS") { //this:State
					action { //it:State
						CommUtils.outblue("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("s(X)"), Term.createTerm("s(0)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurS = 0  
						}
						if( checkMsgContent( Term.createTerm("s(X)"), Term.createTerm("s(1)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurS = 1  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("elabInputA") { //this:State
					action { //it:State
						CommUtils.outblue("$name | elabInputB ${currentMsg.msgContent()}")
						if( checkMsgContent( Term.createTerm("a(X)"), Term.createTerm("a(0)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurA = 0  
						}
						if( checkMsgContent( Term.createTerm("a(X)"), Term.createTerm("a(1)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurA = 1  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
} 
