/* Generated by AN DISI Unibo */ 
package it.unibo.storage

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Storage ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 val math = MathUtils.create()
		 val engine = Prolog()
					
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 var N = 5  
						CommUtils.outgreen("$name | STARTS ")
						 math!!.loadTheory("storage.pl", engine)  
						 val V = math!!.solve("fibo($N,V)","V",engine)  
						CommUtils.outgreen("$name | V=$V ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="elab",cond=whenRequest("getfibo"))
				}	 
				state("elab") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("getfibo(N)"), Term.createTerm("getfibo(N)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val K = payloadArg(0).toLong() 
											   val R = math!!.fiboWithMemo( K,engine )
											   
								answer("getfibo", "getfiboanswer", "getfiboanswer($K,$R)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="elab",cond=whenRequest("getfibo"))
				}	 
			}
		}
} 
