/* Generated by AN DISI Unibo */ 
package it.unibo.ctxbasicrobot
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	//System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "ERROR");
	QakContext.createContexts(
	        "localhost", this, "basicrobot24.pl", "sysRules.pl", "ctxbasicrobot"
	)
	//JAN Facade
	main.java.robotfacade24.Robotfacade24Application.main( arrayOf<String>() );
	//JAN24 Display
}

